### ISSUE TITLE
migrate Projects into Tool

### ISSUE THREAD

**Issue by bbest** [marineenergy/apps#12]

**Comment by bbest** [comment]
See commit https://github.com/mhk-env/mhk-env_shiny-apps/commit/c9d15ebafc86a855ab522a8bf52c3df30aae6059 for code to build initial https://shiny.mhk-env.us/projects.

So far we're using plotly to make a ggplot interactive:

```r
g <- ggplot(...)
plotly::ggplotly(g)
```

Probably going to get more control and less customization with ability to detect clicks and other ui interaction by using native [plotly for R](https://plotly.com/r/), such as [Server-side linking with Shiny | plotly for R](https://plotly-r.com/linking-views-with-shiny.html).

**Comment by bbest** [comment]
Next steps are:
- [ ] pure plotly timeline recreation
- [ ] highlight plotly timeline on click in map per [Leaflet for R - Using Leaflet with Shiny](https://rstudio.github.io/leaflet/shiny.html)

**Comment by Neil-Swanson** [comment]
Notes on progress:

- Created named lists for color scale and symbol scale. Had to create single lists for both the Active/Inactive Project assignment and permit type assignment:

> #pick the color and shape scale

    scale <- RColorBrewer::brewer.pal(n=10, name = 'PiYG') #For permit type
    scale <- scale[c(1:5, 5, 7, 7:10)] #Create discrete values for permit type
    scale2 <- c("#30A4E1", "#999999", scale) #Concatenate with color scale for Active/Inactive Projects
    scale2 <- setNames( #Create named color scale
      scale2, 
      c("Active Project",
        "Inactive Project",
        "Notice of Intent/Preliminary Permit Application",
        "Draft Pilot License App",
        "Final Pilot License App",
        "Pilot License Issued",
        "Draft License App",
        "Draft Re-License App",
        "Final License App",
        "Final Re-License App",
        "Environmental Assessment",
        "Settlement Agreement",
        "Permit Issued"))
    
    shp   <- c(rep('triangle-up', 3), 'triangle-down', 'triangle-up', 'triangle-down', 'triangle-up', 'triangle-down', rep('triangle-up', 3)) #Create shape for permit type symbols
    shp2 <- c(rep(NA, 2), shp) #Concatenate with shapes (NA) for Active/Inactive Projects
    shp2 <- setNames( #Create named shape scale
      shp2, 
      c("Active Project",
        "Inactive Project",
        "Notice of Intent/Preliminary Permit Application",
        "Draft Pilot License App",
        "Final Pilot License App",
        "Pilot License Issued",
        "Draft License App",
        "Draft Re-License App",
        "Final License App",
        "Final Re-License App",
        "Environmental Assessment",
        "Settlement Agreement",
        "Permit Issued"))

![image](https://user-images.githubusercontent.com/45704311/118337668-20ffe700-b4c9-11eb-961a-aa679628128b.png)

- Next steps:
  - Create hover text for data points
  - Bin projects by energy type.  See article below for more details:
![image](https://user-images.githubusercontent.com/45704311/118338015-f4989a80-b4c9-11eb-9d54-d17a73486852.png)
https://plotly.com/r/axes/
  - Add additional projects in Alaska per G. Chang email

**Comment by bbest** [comment]
Fold this and #24 into report generation
