### ISSUE TITLE
Link Title in Existing Reports and arrange by Date

### ISSUE THREAD

**Issue by bbest** [marineenergy/apps#23]
Let's update this DT::datatable so:

- [x] `arrange(desc(date))`
- [x] use link to make title a true link to a new tab `<a href='https://...' target='_blank'>Some Title</a>`; be sure to use `escape = F` to enable HTML in output of datatable

![image](https://user-images.githubusercontent.com/2837257/119889306-3de5e280-beeb-11eb-82ce-f85e028b7aeb.png)

## Code

Here's the code to update:

https://github.com/marineenergy/apps/blob/583785de8f622b6882d2d3434660a11dd913a36f/reports-v2/server.R#L393-L396

Note that `get_rpts_tbl()` is a polling function that returns a data.frame, so you can go (ie `%>%`...) from there.

## RStudio environment

Please choose:

1. Project: `apps_dev` from RStudio:
  ![image](https://user-images.githubusercontent.com/2837257/119889866-f744b800-beeb-11eb-858a-eff9e1437606.png)

1. Branch: `reports-v2`:
  ![image](https://user-images.githubusercontent.com/2837257/119890353-9669af80-beec-11eb-9d88-a1381109da03.png)

## Run/Debug Shiny app

The `reports-v2` there is visible via:

1. https://shiny.marineenergy.app/reports-v2-dev/

1. OR debug by opening `global.R`, `ui.R` or `server.R` and clicking Run App:
  ![image](https://user-images.githubusercontent.com/2837257/119890036-2b1fdd80-beec-11eb-859d-d389febb7360.png)

**Comment by bbest** [comment]
Sorry @cdobbelaere, giving a demo in 10 min and wanted to show this feature so went ahead with fix in a68dd1e

**Comment by cdobbelaere** [comment]
Hi @bbest, no worries - what tasks should I work on instead? Or should I just work on familiarizing myself with the environment?
