### ISSUE TITLE
filter by Technology on Projects Timeline & Map in report-v2

### ISSUE THREAD

**Issue by bbest** [marineenergy/apps#24]
TODO: filter by Technology

![image](https://user-images.githubusercontent.com/2837257/120556158-f9f25200-c3b0-11eb-9007-884ccde1d69c.png)

- [apps (reports-v2 branch in apps_dev): report-v2](https://github.com/marineenergy/apps/tree/reports-v2/report-v2)

https://github.com/marineenergy/apps/blob/48a40ed0f1a9dffbd15b69d3b7efac3e3764b78f/report-v2/global.R#L226

which calls:

https://github.com/marineenergy/apps/blob/48a40ed0f1a9dffbd15b69d3b7efac3e3764b78f/scripts/shiny_report.R#L50-L118

and eventually based on ui.R, these get called in the server.R:

https://github.com/marineenergy/apps/blob/48a40ed0f1a9dffbd15b69d3b7efac3e3764b78f/report-v2/server.R#L130-L139

and finally, these are the functions that do the mapping and plotting of the initial outputs:

https://github.com/marineenergy/apps/blob/48a40ed0f1a9dffbd15b69d3b7efac3e3764b78f/scripts/shiny_report.R#L120-L288

To subsequently filter based on Technology Tags of Interactions, I think we want to use a **Proxy** for both leaflet map and plotly timeline, similar to here:

https://github.com/marineenergy/apps/blob/48a40ed0f1a9dffbd15b69d3b7efac3e3764b78f/report-v2/server.R#L146-L159

**Comment by bbest** [comment]
Now with @cdobbelaere...

## Setup

Copied `/share/github/apps_dev` to `/share/github/apps_cdob` and created a branch `projects-cdob`. Then turned on Shiny app for public viewing (although launching in RStudio is better for debugging):

```bash
# change directory
cd /srv/shiny-server

# switch user and do (sudo) symbolically link (ln -s) the github folder to the shiny app URL
sudo ln -s /share/github/apps_cdob/report-v2 report-v2-cdob
```

Then app served at https://shiny.marineenergy.app/report-v2-cdob/.

## Proxy for leaflet Map

```r
leafletProxy("prj_map", data = filteredData()) %>%
      clearShapes() %>%
      addCircles(radius = ~10^mag/10, weight = 1, color = "#777777",
        fillColor = ~pal(mag), fillOpacity = 0.7, popup = ~paste(mag)
```

## Proxy for plotly Timeline

References:
* [17 Server-side linking with shiny | Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/linking-views-with-shiny.html)
* [plotly 4.7.1 now on CRAN - Carson's blog on R, RStudio, plotly, shiny, data visualization, statistics, etc](https://blog.cpsievert.me/2017/07/13/plotly-4.7.1-now-on-cran/)

**Comment by bbest** [comment]
Next step is to similarly proxy leaflet Timeline plot around here:

https://github.com/marineenergy/apps/blob/5715cda496a0144a02b7703dc9fbe0525e82f02e/report-v2/server.R#L165-L168

## `load_projects()`

https://github.com/marineenergy/apps/blob/5715cda496a0144a02b7703dc9fbe0525e82f02e/scripts/shiny_report.R#L74-L142

## `plot_projects()`

https://github.com/marineenergy/apps/blob/5715cda496a0144a02b7703dc9fbe0525e82f02e/scripts/shiny_report.R#L74-L142

Tips:
1. Note the use of the number of projects per Technology in the y axis given by `n_riv`, `n_tid` and `n_wav`
2. Maybe create helper functions to generate annotations (horizontal black line) and text (Riverine, Wave, Tidal)

**Comment by cdobbelaere** [comment]
Plotly projects timeline now [updates](https://shiny.marineenergy.app/report-v2-cdob) according to selected technology. 
**Ex. 1** Initial plot:  
<img width="638" alt="Screen Shot 2021-07-09 at 12 17 42 PM" src="https://user-images.githubusercontent.com/69017359/125126978-c17d1c80-e0b0-11eb-9cb4-728ad729c5c6.png">
**Ex. 2** Filtering by tidal & wave energy:
![Uploading Screen Shot 2021-07-09 at 12.18.00 PM.png…]()
**Ex. 3** Filtering by riverine & tidal energy:
<img width="633" alt="Screen Shot 2021-07-09 at 12 18 19 PM" src="https://user-images.githubusercontent.com/69017359/125127150-f8533280-e0b0-11eb-9d17-297b8460b98a.png">
