### ISSUE TITLE
Projects Timeline errors out when Interaction added without technology

### ISSUE THREAD

**Issue by bbest** [marineenergy/apps#29]
https://shiny.marineenergy.app/report-v2/

![Screen Shot 2021-07-14 at 2 10 47 PM](https://user-images.githubusercontent.com/2837257/125693529-b3e89eee-cad0-4d11-87ce-93c32ee3f98f.png)

```
Error: An error has occurred. Check your logs or contact the app author for clarification
```

**Comment by cdobbelaere** [comment]
No error generating project timeline when no technology type is selected in interaction. Instead, all 3 technology types are displayed in both project timeline and leaflet map. 
<img width="304" alt="Screen Shot 2021-07-20 at 8 49 16 AM" src="https://user-images.githubusercontent.com/69017359/126355504-52c9d779-a20e-4977-9cd1-e53bb2e9bccf.png">
<img width="411" alt="Screen Shot 2021-07-20 at 8 49 24 AM" src="https://user-images.githubusercontent.com/69017359/126355516-4133253e-b78e-488b-9e27-8f90c0e70c06.png">
