### ISSUE TITLE
Projects Map not updating with 2nd technology when added

### ISSUE THREAD

**Issue by bbest** [marineenergy/apps#30]
https://shiny.marineenergy.app/report-v2/

eg Add Riverine, then add Tidal, only getting Riverine:

![image](https://user-images.githubusercontent.com/2837257/125693936-a27e3d52-a25d-4b1f-92ee-8fc079fff2ca.png)

**Comment by cdobbelaere** [comment]
Map now updates markers accurately regardless of sequence of selected technology types.

Ex: 
**1. First, only wave technology selected.**
<img width="858" alt="Screen Shot 2021-07-20 at 8 53 08 AM" src="https://user-images.githubusercontent.com/69017359/126356060-84052f90-592e-40cb-af9e-9e8785ba5e84.png">

**2. Riverine technology added and markers update accordingly.**
<img width="876" alt="Screen Shot 2021-07-20 at 8 53 17 AM" src="https://user-images.githubusercontent.com/69017359/126356089-87de8be7-e344-4e7c-a4b6-1ecbab93fe28.png">
