### ISSUE TITLE
Too many DB connections

### ISSUE THREAD

**Issue by geocoug** [marineenergy/apps#33]
Unable to connect to database - too many connections. Attempted from pgAdmin, rstudio server psql tool, and [spatial_summaries.Rmd](https://github.com/marineenergy/apps/blob/master/spatial_summaries.Rmd).
![image](https://user-images.githubusercontent.com/48339519/125831210-6b74c9f1-aa52-4b2b-8f9b-a5f51c92aea6.png)

Max DB connections allowed:
![image](https://user-images.githubusercontent.com/48339519/125834141-0c0feff7-c92c-4e6b-a96c-e8dee306af8d.png)

Summary of open connections:
![image](https://user-images.githubusercontent.com/48339519/125834478-e9f23815-f39a-47c9-8870-531682b64e94.png)

Seems to be a single problem query. 89 instances of the following query which is just compiling a list of tables in the database:
`SELECT NULL AS schema, table_name AS table FROM INFORMATION_SCHEMA.tables
WHERE (table_schema = ANY(current_schemas(true))) AND (table_schema <> 'pg_catalog')
UNION ALL
SELECT DISTINCT table_schema AS schema, NULL AS table FROM INFORMATION_SCHEMA.tables`
Most instances were created on 2021-06-29 or 2021-06-30.

Not sure why this query is being executed, or what for. Do we need [connection pooling](https://www.enterprisedb.com/blog/postgresql-pgpool-connection-pool-database-load)? - like  [PgPool](https://pgpool.net/mediawiki/index.php/Main_Page).

---

Temporary fix to remove sessions:
`
select pg_terminate_backend(pid)
from pg_stat_activity
where pid != pg_backend_pid() and datname = 'gis' and usename = 'admin' and state = 'idle';
`

**Comment by bbest** [comment]
Yep, I had a similar problem and used [`pool::dbPool()`](https://db.rstudio.com/r-packages/pool/) here (so far just reports-v2 branch):

https://github.com/marineenergy/apps/blob/1a52acf702322768aec8f62b162bbf02f3bfea15/scripts/db.R#L38

**Comment by bbest** [comment]
Now that it's merged, report-v2 should be working without this issue popping up
