### ISSUE TITLE
Projects: fly to project marker in Map when project clicked on Timeline

### ISSUE THREAD

**Issue by bbest** [marineenergy/apps#34]
Right you are, Grace! That functionality seems to have gotten commented out here:

https://github.com/marineenergy/apps/blob/b229aa3db26c2f4256ff1e8f2ffe74cf013dac46/report-v2/server.R#L375-L390 

@cdobbelaere, can you please uncomment to get this going again? Perhaps some `HelpText()` could be added to indicate this functionality.

----
From: Grace 

Hey Ben,

I’m playing around with Projects on this page and thought there was interactivity between the Timeline and Map where the pin on the map would be highlighted with zoom-in if a project is selected on the Timeline. This doesn’t seem to happen anymore. Or am I delusional?

 

Thanks,

-G

**Comment by cdobbelaere** [comment]
Plotly click now causes map to fly to corresponding project marker.
<img width="416" alt="Screen Shot 2021-07-20 at 8 45 02 AM" src="https://user-images.githubusercontent.com/69017359/126354794-20392e69-3983-42cc-9220-00162969df01.png">
<img width="420" alt="Screen Shot 2021-07-20 at 8 45 14 AM" src="https://user-images.githubusercontent.com/69017359/126354689-968a5850-abaf-4977-ae63-1d24275b9f7c.png">
