### ISSUE TITLE
Edit app error: Disconnected from the server. Reload 

### ISSUE THREAD

**Issue by bbest** [marineenergy/apps#63]
Hi @cdobbelaere,

Sharon is getting disconnected when clicking **Edit** after selecting a row:

- Disconnected from the server. **Reload**
   ![image](https://user-images.githubusercontent.com/2837257/137391497-d469612f-f9a4-44de-b050-2386df21a4df.png)

Here's the error I get when clicking on **Edit** button after running the `edit/` app (under `/share/github/apps`, master branch) from [https://rstudio.marineenergy.app](rstudio.marineenergy.app):

```
Warning: Error in &&: invalid 'y' type in 'x && y'
```

But this happens before reaching inside the `ferc.update.callback()` function:

```r
ferc.update.callback <- function(data, olddata, row) {
  browser()
  ...
```

Any ideas where this might be happening? Perhaps a `filter()` statement with multiple arguments that get an `&&` applied so all have to evaluate to TRUE.

**Comment by cdobbelaere** [comment]
Hi @bbest, thanks for checking in on that. I'll look into the callback and see what's going on.
