### ISSUE TITLE
handle missing nested Tags

### ISSUE THREAD

**Issue by bbest** [marineenergy/apps#94]
## Problem

From [MarineEnergy.app_Review_GCS_120921.docx - Google Docs](https://docs.google.com/document/d/1tTB_o1ULR_1FH4qAZ-x5x_IFVoFHaFHX/edit#heading=h.xeom76c51guy):

> If a user gets really specific and selects, e.g., Tidal, Physical Interaction/Changes in Flow, Fish/Pelagic Fish, no results appear on any of the pages. There’s an issue with the way Tethys Knowledge Base publications are tagged. For example: If one selects Tidal, Physical Interaction, and Fish, there are 33 entries in Management Measures, 221 FERC Docs, and 0 Tethys Publications. If one selects Tidal and Fish, or Tidal and Fish and Collision, no Tethys Publications appear. But with Current and Fish and Collision or just Fish and Collision, there are 479 hits. We need to figure out what to do about this. For example, if no results appear, have a statement appear, like, “No results found. Recommend a broader search (e.g., Current instead of Tidal or Noise instead of Noise/Underwater.” Or we implement code that automatically searches the next category up on the hierarchy and let the user know that this has been implemented.

## Update filter for content based on available tags

- select Stressor `Noise/Underwater`
  - see reasonable results in **Management**
  - see a message in **Publications** about how Stressor `Noise/Underwater` got replaced by parent tag Stressor `Noise` in filter since tagging in Publications did not resolve to Stressor `Noise/Underwater`

## Message based on content

A la https://github.com/marineenergy/apps/issues/93:
![](https://user-images.githubusercontent.com/2837257/147005160-9ad36d15-abd8-417d-99b8-ec81f2fc86c8.png)

**Comment by bbest** [comment]
## Sequence of shiny app `report-v2` operations

* [global.R](https://github.com/marineenergy/apps/blob/08e53e9d909b1dff53341867266225b2b65d84e4/report-v2/global.R)
  - [sources](https://github.com/marineenergy/apps/blob/08e53e9d909b1dff53341867266225b2b65d84e4/report-v2/global.R#L9) [shiny_report.R](https://github.com/marineenergy/apps/blob/08e53e9d909b1dff53341867266225b2b65d84e4/scripts/shiny_report.R)
    * loads `get_{content}_tbl()` functions
    * loads {content} tables with all tags, like `d_pubs_tags`
* [ui.R](https://github.com/marineenergy/apps/blob/08e53e9d909b1dff53341867266225b2b65d84e4/report-v2/ui.R)
  - `dataTableOutput("tbl_pubs")`
* [server.R](https://github.com/marineenergy/apps/blob/08e53e9d909b1dff53341867266225b2b65d84e4/report-v2/server.R)
  - `output$tbl_pubs <- renderDataTable({ get_pubs() ... })`
  - `get_pubs <- reactive({ get_pubs_tbl(d_pubs_tags, ixns = values$ixns) })`
* [shiny_report.R](https://github.com/marineenergy/apps/blob/08e53e9d909b1dff53341867266225b2b65d84e4/scripts/shiny_report.R)
  - [`get_pubs_tbl()`](https://github.com/marineenergy/apps/blob/08e53e9d909b1dff53341867266225b2b65d84e4/scripts/shiny_report.R#L350-L369)
    * `tag_cats <-  get_content_tag_categories("publications")`
    * `get_rowids_with_ixn(ixns, db_tbl = "tethys_pub_tags", categories = tag_cats)`
    * [`get_rowids_with_ixn()`](https://github.com/marineenergy/apps/blob/08e53e9d909b1dff53341867266225b2b65d84e4/scripts/shiny_report.R#L371-L392)
      - `# subset interactions by categories available to content type`
      - Similarly can update tags based on those that don't have children in the parent when the tag is nested, ie `d_pubs_tags` does not have `Stressor.Noise.Underwater` or any `Stressor.Noise.*` children.

You'll probably want to use direct SQL, ie `DBI::getQuery()` to take advantage of the Postgres ltree querying to ask whether any children exist. Here's some further reference:

* [ltree: store tags as hierarchically labelled tree in postgres · Issue #17 · marineenergy/apps](https://github.com/marineenergy/apps/issues/17)

* show existing `d_pubs_tags` as SQL:
  ```r
  d_pubs_tags %>%  dplyr::show_query()
  ```
  shows:
  ```sql
  SELECT DISTINCT "rowid", "uri", "title", "tag", "tag_category", "tag_sql"
    FROM (
      SELECT "LHS"."rowid" AS "rowid", "uri", "title", "tag", "tag_category", "tag_sql"
        FROM (
         SELECT "rowid", "uri", "title"
           FROM "tethys_pubs") "LHS"
           LEFT JOIN (
             SELECT "tag", "rowid", "tag_category", "tag_sql"
             FROM "tethys_pub_tags") "RHS"
             ON ("LHS"."rowid" = "RHS"."rowid")
```

**Comment by bbest** [comment]
Pseudocode:

```r
# if "Stressor.Noise.Underwater" not in "tethys_pub_tags" & has level > 2
# then check if higher level exists. if so, update to that one and share message
```

Trick:

```r
dput(ixns) # to output variable
```

**Comment by bbest** [comment]
![image](https://user-images.githubusercontent.com/2837257/149230226-3a508496-8623-4ee7-923a-4057cb5a5f5b.png)

**Comment by bbest** [comment]
Cristina's current approach:

https://github.com/marineenergy/apps/blob/34b378c5c4e374d6c2672b7ce40205db8bb2f452/scripts/shiny_report.R#L455-L461

The problem currently is that per https://github.com/marineenergy/apps/issues/106#issuecomment-1015582361 we need both of these `intxns` filtering processes to happen per content type, ideally with messages back to the user:

1. **_Drop non-applicable tag categories_**, ie dropping `Consequence.Collision` tag from interactions querying Publications since this content type lacks the `Consequence` category; and

2. **_Convert missing child tags to parents_**, ie converting `Stressor.Noise.Underwater` to `Stressor.Noise` with Publications since this content type only has the parent Noise tag.

```r
# filter ixns by content type
ixns_pubs <– get_ixns_for_content(ixns, "publications") # add attributes with messages

# get rows of content by ixns
rowids <- sapply(ixns_pubs, get_rowids_with_ixn, db_tbl = "tethys_pub_tags", categories = tag_cats) %>%
      unlist() %>% unique()
    d <- d %>%
      filter(rowid %in% !!rowids)


```

And still need to produce an output in `server.R` per content type like:

- https://github.com/marineenergy/apps/blob/34b378c5c4e374d6c2672b7ce40205db8bb2f452/report-v2/ui.R#L132-L134
- https://github.com/marineenergy/apps/blob/34b378c5c4e374d6c2672b7ce40205db8bb2f452/report-v2/server.R#L329-L337

**Comment by cdobbelaere** [comment]
Tags with non-applicable tag categories are now dropped from interactions, but messages demonstrating modifications to missing child tags are now appearing even when there is a NULL message attribute in the corresponding data. 

When Noise/Underwater and Fish/DemersalFish are selected, the message on the Publications page appears as expected:
<img width="1464" alt="Screen Shot 2022-01-20 at 5 39 56 PM" src="https://user-images.githubusercontent.com/69017359/150450300-c6a73cb5-2f1e-4b56-9ea1-a9c9314f9441.png">

However, there is a message on both the Documents and Management pages, even though there is data to match the tags in the interaction. This message should not appear at all, but instead it appears as follows:
<img width="1446" alt="Screen Shot 2022-01-20 at 5 40 09 PM" src="https://user-images.githubusercontent.com/69017359/150450290-f43c0cfe-5104-49e5-b59a-3da33a1a2455.png">

**Comment by bbest** [comment]
Looks like this is working fine with latest overhaul
